version: '3.8'
services:
  signaling:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /home/evan/webrtc/server/certs/
        target: /certs/
    restart: always
